### ISSUE TITLE
raise KeyError("Missing utterance {}!".format(index)) KeyError: 'Missing utterance clnsp1!'

### ISSUE THREAD

**Issue by mnabihali** [funcwj/conv-tasnet#8]
Traceback (most recent call last):
  File "train.py", line 86, in <module>
    run(args)
  File "train.py", line 50, in run
    trainer.run(train_loader, dev_loader, num_epochs=args.epochs)
  File "/hardmnt/moissan0/home/mnabih/piccadilly0/home/mnabih/PycharmProjects/Co/nnet/libs/trainer.py", line 215, in run
    cv = self.eval(dev_loader)
  File "/hardmnt/moissan0/home/mnabih/piccadilly0/home/mnabih/PycharmProjects/Co/nnet/libs/trainer.py", line 203, in eval
    for egs in data_loader:
  File "/hardmnt/moissan0/home/mnabih/piccadilly0/home/mnabih/PycharmProjects/Co/nnet/libs/dataset.py", line 143, in __iter__
    for chunks in self.eg_loader:
  File "/hardmnt/moissan0/home/mnabih/piccadilly0/home/mnabih/PycharmProjects/Co/lib64/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/hardmnt/moissan0/home/mnabih/piccadilly0/home/mnabih/PycharmProjects/Co/lib64/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/hardmnt/moissan0/home/mnabih/piccadilly0/home/mnabih/PycharmProjects/Co/lib64/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/hardmnt/moissan0/home/mnabih/piccadilly0/home/mnabih/PycharmProjects/Co/lib64/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/hardmnt/moissan0/home/mnabih/piccadilly0/home/mnabih/PycharmProjects/Co/lib64/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/hardmnt/moissan0/home/mnabih/piccadilly0/home/mnabih/PycharmProjects/Co/lib64/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/hardmnt/moissan0/home/mnabih/piccadilly0/home/mnabih/PycharmProjects/Co/lib64/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/hardmnt/moissan0/home/mnabih/piccadilly0/home/mnabih/PycharmProjects/Co/nnet/libs/dataset.py", line 42, in __getitem__
    ref = [reader[key] for reader in self.ref]
  File "/hardmnt/moissan0/home/mnabih/piccadilly0/home/mnabih/PycharmProjects/Co/nnet/libs/dataset.py", line 42, in <listcomp>
    ref = [reader[key] for reader in self.ref]
  File "/hardmnt/moissan0/home/mnabih/piccadilly0/home/mnabih/PycharmProjects/Co/nnet/libs/audio.py", line 119, in __getitem__
    raise KeyError("Missing utterance {}!".format(index))
KeyError: 'Missing utterance clnsp10!'

**Comment by yudashuixiao1** [comment]
hi，did you fix the problem? I also meet that.

**Comment by elton11142** [comment]
> hi，did you fix the problem? I also meet that.

您好，我想请问下Conv tasnet模型你最后实现成功了吗
